#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "$DOT_FILES/prezto/runcoms/general.zsh"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source "$DOT_FILES/prezto/runcoms/keys.sh"
source "$DOT_FILES/prezto/runcoms/aliases.sh"
source "$DOT_FILES/prezto/runcoms/functions.sh"
